搜索模块添加
ecodeclub/webook pull request #128
Opened 2024-05-04 14:25 UTC by juniaoshaonian

2024-05-05 13:26 UTC, longyue0521 requested changes

2024-05-05 13:26 UTC, longyue0521 commented on internal/cases/internal/event/event.go
> +package event
检查所有文件, 添加开源license文件头

2024-05-05 13:26 UTC, longyue0521 commented on internal/cases/internal/service/cases.go
> +const defaultSyncTimeout = 10 * time.Second
改为Service内部的一个字段, 类比于logger

2024-05-05 13:26 UTC, longyue0521 commented on internal/cases/wire.go
> +		initSyncEventProducer,
可以直接用event.NewSyncEventProducer, 因为InitModule返回值有error

2024-05-06 14:35 UTC, flycash commented
我先合并了。

2024-05-06 14:35 UTC, merged