添加点赞收藏模块
ecodeclub/webook pull request #137
Opened 2024-05-09 15:17 UTC by juniaoshaonian

2024-05-10 03:38 UTC, longyue0521 requested changes

2024-05-10 03:38 UTC, longyue0521 commented on internal/interactive/internal/domain/interactive.go
> +package domain
添加license

2024-05-10 03:38 UTC, longyue0521 commented on internal/interactive/internal/events/interactive.go
> +}
1. 改为包内可见, event包外只需要知道Consumer和Event
2. 可以考虑改为函数式编程, 将代码内聚到Consumer中
```go
type handleFunc  (ctx context.Context, evt Event) error

func (s *Consumer) getViewHandleFunc() handleFunc {
   return handleFunc(func (ctx context.Context, evt Event) error {
        return s.svc.IncrReadCnt(ctx, evt.Biz, evt.BizId)
   })
}

s.handlerMap := map[string]handleFunc {
     "view": s.getViewHandleFunc(),
} 
```

2024-05-10 03:38 UTC, longyue0521 commented on internal/interactive/internal/integration/integration_test.go
> +			wantCode: 500,
1. 改为同一用户多次点赞,只记录一次
2. after要证明, 确实记录一次

2024-05-10 03:38 UTC, longyue0521 commented on internal/interactive/internal/integration/integration_test.go
> +			name: "多次收藏失败",
after中要证明数据状态与之前一样, 500 你不无法确定是什么原因导致的失败

2024-05-10 03:38 UTC, longyue0521 commented on internal/interactive/internal/integration/integration_test.go
> +			name: "浏览",
测试名携带信息太少, 需要看代码才能明白测什么场景.

1. 用户首次浏览资源 资源浏览计数加1
2. 用户重复浏览资源 资源浏览计数加1

以上面为例, 从用户场景角度出发, 重新思考/改写各个测试的名称, 携带足够信息

2024-05-10 03:51 UTC, longyue0521 requested changes

2024-05-10 03:51 UTC, longyue0521 commented on internal/interactive/internal/repository/dao/interactive.go
> +			DoUpdates: clause.Assignments(map[string]interface{}{
替换所有 interface{} 为 any

2024-05-10 03:51 UTC, longyue0521 commented on internal/interactive/internal/repository/dao/type.go
> +	// 收藏夹的ID
去掉过期注释

2024-05-10 03:51 UTC, longyue0521 commented on internal/interactive/internal/repository/dao/type.go
> +func (UserCollectionBiz) TableName() string {
你看看你之前写的模块中 数据库表结构体的 TableName是不是都被重构了, 如果是 就去掉

2024-05-10 23:41 UTC, longyue0521 requested changes

2024-05-10 23:41 UTC, longyue0521 commented on internal/interactive/internal/events/consumer.go
> +		"view":    viewHandle,
既然用了函数式编程,可以将各个handleFunc内聚到Consumer上,

```go
type handleFunc func (ctx context.Context, evt Event) error

s.handlerFuncMap := map[string]handleFunc {
   "like": s.likeHandleFunc(),
   //....
}

func (s *Consumer) likeHandleFunc() handleFunc {
return handleFunc(func (ctx context.Context, evt Event) error {
    s.svc.Like(ctx, evt.Biz, evt.BizId, evt.Uid)
})
}

```

2024-05-10 23:41 UTC, longyue0521 commented on internal/interactive/internal/integration/integration_test.go
> +			name: "用户点赞一次，有一条记录，计数加一",
这里的 “有一条记录” 是实现层面的在数据库层面只为其创建一条数据的意思吗? 如果是 不要这么写, 不要透底层实现

改为 用户点赞一次 该用户的点赞统计数加一

2024-05-10 23:41 UTC, longyue0521 commented on internal/interactive/internal/integration/integration_test.go
> +			name: "同一用户多次点赞,只记录一次",
与上面的测试描述一起看, 这里的“记录一次”有歧义. 改为 用户重复点赞 该用户的点赞统计数不变

2024-05-10 23:41 UTC, longyue0521 commented on internal/interactive/internal/integration/integration_test.go
> +			name: "用户收藏一次，有一条记录，计数加一",
参照上面的修改, 修改收藏计数测试描述

2024-05-10 23:41 UTC, longyue0521 commented on internal/interactive/internal/integration/integration_test.go
> +			name: "用户点赞过的详情",
用户点赞过的 [详情 “什么”] ? 数? 还是获取某详情上的统计/计数信息?

获取被赞过的详情计数信息?

2024-05-10 23:41 UTC, longyue0521 commented on internal/interactive/internal/integration/integration_test.go
> +			name: "用户收藏过的详情",
获取被收藏过的详情的计数信息?

2024-05-10 23:43 UTC, longyue0521 commented
修一下 ci中的报错信息

2024-05-11 07:48 UTC, flycash commented on internal/interactive/internal/repository/interactive.go
> +	if err != nil {
如果数据不存在，说明这是一个新的内容，没有任何人观看过，那么你就不要返回 error，而是返回所有的 interactive{}

2024-05-11 07:48 UTC, flycash commented on internal/interactive/internal/web/handler.go
>  	g.POST("/cnt", ginx.BS[GetCntReq](h.GetCnt))
提供一个批量接口，参数是 biz 和 []id。返回 map[id]Interactive 这种数据。

2024-05-11 23:26 UTC, merged