case,question支持status
ecodeclub/webook pull request #90
Opened 2024-04-11 14:34 UTC by juniaoshaonian

2024-04-11 14:43 UTC, longyue0521 requested changes

2024-04-11 14:43 UTC, longyue0521 commented on internal/cases/internal/domain/cases.go
> +	PublishedStatus CaseStatus = 2
UnpublishedStatus, PublishedStatus

2024-04-11 14:43 UTC, longyue0521 commented on internal/cases/internal/integration/handler_test.go
> +					Status:    1,
使用UnpublishedStatus替换魔数, 替换所有同类问题

2024-04-11 14:43 UTC, longyue0521 commented on internal/question/internal/domain/question.go
> +	PublishedStatus QuestionStatus = 2
同上

2024-04-11 14:43 UTC, longyue0521 commented on internal/question/internal/integration/handler_test.go
> +					Status:  1,
同上

2024-04-12 04:02 UTC, flycash reviewed
我想到一个问题，你把 default 1 都去掉。因为我们这个用了衍生类型，Question 和 PublishedQuestion，按照道理，Question 默认值是 1，但是 PublishedQuestion 应该是 2。所以还是等我手动更新数据库吧。

把 case 和 question 的默认值都去掉

2024-04-13 03:58 UTC, flycash approved these changes

2024-04-13 03:59 UTC, merged